name: ubuntu-22.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: make set-version
    - uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: |
          ${{github.workspace}}/build/
          !${{github.workspace}}/build/bin
        key: ${{ runner.os }}-${{ hashFiles('CMakeLists.txt') }}

    - run: sudo apt update && sudo apt install -y --no-install-recommends build-essential libtool cmake curl debconf-utils git liblua5.2-0 liblua5.2-dev libmariadb-dev libssl-dev minizip make mariadb-client locales nano open-vm-tools unzip uuid-dev iputils-ping wget libcurl4-openssl-dev gdb libyaml-cpp-dev ccache ninja-build pv mariadb-server libboost-dev
    - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEQEMU_BUILD_LOGIN=ON -DEQEMU_BUILD_TESTS=OFF -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja
    - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - run: make test
    - uses: actions/cache/save@v3
      if: github.ref == 'refs/heads/main'
      with:
        path: |
          ${{github.workspace}}/build/
          !${{github.workspace}}/build/bin
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}

    - name: Archive Release
      if: github.ref == 'refs/heads/main'
      uses: thedoctor0/zip-release@main
      with:
        path: './build/bin/'
        type: 'tar'
        filename: 'linux.${{ env.VERSION }}.tar.gz'

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "${{ env.VERSION }}"
        prerelease: false
        title: "${{ env.VERSION }}"
        files: |
          linux.${{ env.VERSION }}.tar.gz
