name: ubuntu-22.04

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: make set-version-${{github.run_number}}

    - run: sudo apt install -y --no-install-recommends build-essential libtool cmake curl ccache debconf-utils git liblua5.1-0 liblua5.1-0-dev libluabind-dev libmysql++-dev libmysqlclient-dev libssl-dev lua5.1 minizip make mariadb-client locales nano open-vm-tools unzip uuid-dev iputils-ping wget libcurl4-openssl-dev gdb libyaml-cpp-dev ninja-build
    - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEQEMU_BUILD_LOGIN=ON -DEQEMU_BUILD_TESTS=OFF -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja
    - uses: lukka/get-cmake@latest
    - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        path: './build/bin/'
        type: 'tar'
        filename: 'linux-latest.tar.gz'

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "${{env.VERSION}}"
        prerelease: true
        title: "${{env.VERSION}}"
        files: |
          linux-latest.tar.gz